name: Build WhatsAppEmoji

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes zopfli pngquant
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Build WhatsAppEmoji
      run: |
        make -j
        make install

    - name: Upload .ttf file
      uses: actions/upload-artifact@v4
      with:
        name: WhatsAppEmoji
        path: build/WhatsAppEmoji.ttf

