name: Build WhatsAppEmoji

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.13"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4 # https://github.com/actions/checkout

    - name: Set up Python
      uses: actions/setup-python@v5 # https://github.com/actions/setup-python
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install --yes zopfli pngquant imagemagick
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Build WhatsAppEmoji
      run: |
        make -j
        make install

    - name: Upload .ttf file
      uses: actions/upload-artifact@v4 # https://github.com/actions/upload-artifact
      with:
        name: WhatsAppEmoji
        path: build/WhatsAppEmoji.ttf

